<?php

namespace AppBundle\Repository;

/**
 * administratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class administratorRepository extends \Doctrine\ORM\EntityRepository
{
    function findMyself($id){
        return $this->createQueryBuilder('a')
            ->andWhere('a.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
