<?php

namespace AppBundle\Repository;

/**
 * categoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoriesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrdered()
    {
        $qb = $this->createQueryBuilder('cat')
            ->addOrderBy('cat.name', 'ASC');
        $query = $qb->getQuery();
        return $query->execute();
    }
}
