<?php

namespace AppBundle\Repository;

/**
 * gamesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class gamesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllGames()
    {
        $qb = $this->createQueryBuilder('cat')
            ->addOrderBy('cat.name', 'ASC');
        $query = $qb->getQuery();
        return $query->execute();
    }

    public function findByString($searchString){

        $qb = $this->createQueryBuilder('u')
            ->where('u.name LIKE :nom')
            ->setParameter('nom', '%'.$searchString.'%');
        $query = $qb->getQuery();
        return $query->execute();
    }
}
