<?php

namespace AppBundle\Repository;

/**
 * gamesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class gamesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllGames()
    {
        $qb = $this->createQueryBuilder('cat')
            ->addOrderBy('cat.name', 'ASC');
        $query = $qb->getQuery();
        return $query->execute();
    }
}
